### ISSUE TITLE
I want to change a specific linked column to a hand cursor rather than a regular arrow cursor.

### ISSUE THREAD

**Issue by jhj0088** [nhn/tui.grid#1598]
I want to change a specific linked column to a hand cursor rather than a regular arrow cursor.
Is it possible?

**Comment by jajugoguma** [comment]
@jhj0088 
How about adding a class name to the column and styling the cursor for it?

```css
.linked-column {
  cursor: grab; /* or what you want */
}
```

```js
const grid = new tui.Grid({
  // ...
  columns: [
    {
      name: 'linkedColumn',
      className: 'linked-column',
    },
    // ...
  ]
  // ...
});
```
